name: Check coding style

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Check
        uses: psf/black@stable
        with:
          version: "24.4.2"

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake8
        run: |
          pip install flake8==7.1.0
      - name: run flake8
        run: |
          flake8 . --count --show-source --statistics
